# Generated by Django 3.0.8 on 2020-07-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_lisiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lisiting',
            name='author',
        ),
    ]
