# Generated by Django 3.0.8 on 2020-07-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200714_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='img',
            new_name='image',
        ),
    ]
