# Generated by Django 3.0.8 on 2020-07-15 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200715_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='min_bid',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Listing'),
        ),
    ]
