# Generated by Django 3.0.8 on 2020-07-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200716_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='min_bid',
            field=models.FloatField(),
        ),
    ]
