# Generated by Django 3.0.8 on 2020-07-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200716_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Fashion & Beauty', 'Fashion & Beauty'), ('Health', 'Health'), ('Beauty', 'Beauty'), ('Sports', 'Sports'), ('Home & Garden', 'Home & Garden')], max_length=25),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
