# Generated by Django 3.0.8 on 2020-07-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200716_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidder',
        ),
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion & Beauty', 'Fashion & Beauty'), ('Health', 'Health'), ('Beauty', 'Beauty'), ('Sports', 'Sports'), ('Home & Garden', 'Home & Garden'), ('Others', 'Others')], default='Others', max_length=25),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='noimage.jpg', upload_to='media'),
        ),
    ]
