# Generated by Django 3.0.8 on 2020-07-18 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20200718_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='min_bid',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
