# Generated by Django 3.0.8 on 2020-07-21 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20200720_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.Listing'),
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
